site_name: galexrt Docs
site_url: 'https://docs.galexrt.moe'
repo_url: https://github.com/galexrt/docs.galexrt.moe
edit_uri: edit/main/docs/
site_author: Alexander Trost
site_description: "galexrt tips, tricks, cheat sheets and documentation stuff."
use_directory_urls: true
copyright: '<a href="/site-notice/">Impressum</a> | <a href="/privacy-policy/">Privacy Policy</a> | This work is licensed under a <a href="https://creativecommons.org/licenses/by-sa/4.0/">Creative Commons Attribution 4.0 International License</a>'
theme:
  name: material
  font: false
  favicon: images/favicon.png
  logo: images/favicon.png
  palette:
    - scheme: 'default'
      primary: 'deep purple'
      accent: 'deep orange'
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: 'slate'
      primary: 'deep purple'
      accent: 'red'
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github
  features:
    - content.tabs.link
    - instant
    - navigation.expand
    - navigation.indexes
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - tabs
extra_css:
  - stylesheets/extra.css
plugins:
  - search
  # Removed in material mkdocs 6.0
  # See https://squidfunk.github.io/mkdocs-material/deprecations/#bundled-plugins
  #- awesome-pages
  #- git-revision-date-localized
  - minify:
      minify_html: true
      minify_js: true
      htmlmin_opts:
        remove_comments: true
      #js_files: []
  - redirects:
      redirect_maps: {}
markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - footnotes
  - meta
  - toc:
      permalink: true
  - tables
  - nl2br
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight:
      use_pygments: true
      linenums: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.snippets
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed
