name: build-and-deploy
on:
  push:
    branches:
      - master
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    container:
      image: "ghcr.io/galexrt/mkdocs-material-insiders"
      credentials:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.GHCR_TOKEN }}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: false
      - name: Build
        run: |
          mkdocs build --clean
      - name: Deploy to GitHub pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site
          cname: docs.galexrt.moe
